export const colours = {
    foreground: {
        black: "\x1b[30m",
        darkRed: "\x1b[31m",
        darkGreen: "\x1b[32m",
        darkYellow: "\x1b[33m",
        darkBlue: "\x1b[34m",
        darkMagenta: "\x1b[35m",
        darkCyan: "\x1b[36m",
        darkWhite: "\x1b[37m",
        brightBlack: "\x1b[90m",
        lightRed: "\x1b[91m",
        lightGreen: "\x1b[92m",
        lightYellow: "\x1b[93m",
        lightBlue: "\x1b[94m",
        lightMagenta: "\x1b[95m",
        lightCyan: "\x1b[96m",
        white: "\x1b[97m",
    },
    background: {
        black: "\x1b[40m",
        darkRed: "\x1b[41m",
        darkGreen: "\x1b[42m",
        darkYellow: "\x1b[43m",
        darkBlue: "\x1b[44m",
        darkMagenta: "\x1b[45m",
        darkCyan: "\x1b[46m",
        darkWhite: "\x1b[47m",
        brightBlack: "\x1b[100m",
        lightRed: "\x1b[101m",
        lightGreen: "\x1b[102m",
        lightYellow: "\x1b[103m",
        lightBlue: "\x1b[104m",
        lightMagenta: "\x1b[105m",
        lightCyan: "\x1b[106m",
        white: "\x1b[107m",
    },
    bold: "\x1b[1m",
    underline: "\x1b[4m",
    noUnderline: "\x1b[24m",
    reverse: "\x1b[7m",
    positive: "\x1b[27m",
    default: "\x1b[0m"
}
